/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.enerfrisoft.anularRemesa;

import com.enerfrisoft.dao.DataSourceClass;
import com.enerfrisoft.error.QueryError;
import com.enerfrisoft.modal.Modal;
import com.enerfrisoft.remesa.RecordRemesa;
import com.enerfrisoft.tools.Data;
import com.enerfrisoft.tools.UniversalDAO;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author sebastianaf
 */
public class FormAnularRemesa extends javax.swing.JFrame {

    private String username;
    TextAutoCompleter acConsecutivoRemesa;
    private DataSourceClass dataSource;
    private Connection conn;
    private Connection defaultServerConn;

    public FormAnularRemesa(String username, DataSourceClass dataSource,Connection conn) {
        this.conn = conn;
        this.dataSource = dataSource;
        this.username = username;
        initComponents();
        com.enerfrisoft.tools.Visual.windowIcon(this);
        buildAutoCompleterConsecutivoRemesa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        consecutivoRemesa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        motivoAnulacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        remitente = new javax.swing.JTextField();
        destinatario = new javax.swing.JTextField();
        fechaDeRegisto = new javax.swing.JTextField();
        anularRemesa = new javax.swing.JButton();
        CODMOTIVOANULACION = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anular Remesa");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Anular remesa");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Indique el consecutivo");

        jLabel5.setText("Motivo de anulación");

        motivoAnulacion.setModel(UniversalDAO.getComboBoxModel("select * from motivo_anulacion_remesa", conn)
        );
        motivoAnulacion.setSelectedItem(null);
        motivoAnulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivoAnulacionActionPerformed(evt);
            }
        });

        jLabel2.setText("Remitente");

        jLabel3.setText("Destinatario");

        jLabel6.setText("Fecha de registro");

        jLabel7.setText("Observaciones");

        observaciones.setColumns(20);
        observaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        observaciones.setLineWrap(true);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        remitente.setEditable(false);

        destinatario.setEditable(false);

        fechaDeRegisto.setEditable(false);

        anularRemesa.setText("Anular remesa");
        anularRemesa.setEnabled(false);
        anularRemesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularRemesaActionPerformed(evt);
            }
        });

        CODMOTIVOANULACION.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(motivoAnulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CODMOTIVOANULACION, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                    .addComponent(consecutivoRemesa)
                                    .addComponent(remitente)
                                    .addComponent(destinatario)
                                    .addComponent(fechaDeRegisto))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(anularRemesa)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(motivoAnulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CODMOTIVOANULACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(consecutivoRemesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(remitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fechaDeRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anularRemesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buildAutoCompleterConsecutivoRemesa() {
        acConsecutivoRemesa = new TextAutoCompleter(consecutivoRemesa, new AutoCompleterCallback() {
            @Override
            public void callback(Object o) {
                String sRemitente = UniversalDAO.getString(""
                        + "select tercero.NOMIDTERCERO "
                        + "from tercero inner join remesa "
                        + "on tercero.NUMIDTERCERO = remesa.NUMIDREMITENTE "
                        + "where remesa.CONSECUTIVOREMESA = '" + o.toString() + "'", conn);
                remitente.setText(sRemitente);

                String sDestinatario = UniversalDAO.getString(""
                        + "select tercero.NOMIDTERCERO "
                        + "from tercero inner join remesa "
                        + "on tercero.NUMIDTERCERO = remesa.NUMIDDESTINATARIO "
                        + "where remesa.CONSECUTIVOREMESA = '" + o.toString() + "'", conn);
                destinatario.setText(sDestinatario);

                String fechaRegistro = UniversalDAO.getStringPre(""
                        + "SET lc_time_names = 'es_ES';",
                        "select DATE_FORMAT(dateLog,'%W %d de %M del %Y %r') "
                        + "from remesa "
                        + "where CONSECUTIVOREMESA='" + o.toString() + "'", conn);
                fechaDeRegisto.setText(fechaRegistro);
                
                if(motivoAnulacion.getSelectedItem()!=null){
                    anularRemesa.setEnabled(true);
                }
            }
        });
        ArrayList<String> data = UniversalDAO.getArrayList(""
                + "select remesa.CONSECUTIVOREMESA "
                + "from remesa "
                + "where estado='activo' "
                + "and manifiestoConsecutivo is NULL "
                + "order by CONSECUTIVOREMESA ASC", conn);
        if(data.size()==0){
            Modal.show("Información", "No hay remesas por anular", this, "", "information");
        }
        for (int i = 0; i < data.size(); i++) {
            acConsecutivoRemesa.addItem(data.get(i));
        }
    }

    private void anularRemesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularRemesaActionPerformed
        try {
            Thread registro = new Thread(new RecordAnularRemesa(getValues(), this, consecutivoRemesa.getText(), dataSource, conn));
            registro.start();
        } catch (Exception e) {
            Thread report = new Thread(new QueryError(new com.enerfrisoft.error.Error(e)));
            report.start();
        }
    }//GEN-LAST:event_anularRemesaActionPerformed

    private void motivoAnulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivoAnulacionActionPerformed
        if (motivoAnulacion.getSelectedItem() != null) {
            CODMOTIVOANULACION.setText(UniversalDAO.getString(""
                    + "select cod "
                    + "from motivo_anulacion_remesa "
                    + "where nombre='" + motivoAnulacion.getSelectedItem().toString() + "';", conn));
        }
    }//GEN-LAST:event_motivoAnulacionActionPerformed

    private AnularRemesa getValues() {
        AnularRemesa anularRemesa = new AnularRemesa();
        Data.auth(anularRemesa, conn);
        anularRemesa.setMOTIVOREVERSAREMESA("A");
        anularRemesa.setCONSECUTIVOREMESA(consecutivoRemesa.getText());
        anularRemesa.setMOTIVOANULACIONREMESA(CODMOTIVOANULACION.getText());
        anularRemesa.setOBSERVACIONES(observaciones.getText());
        anularRemesa.setUserLog(username);
        anularRemesa.setEstado("activo");

        return anularRemesa;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAnularRemesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAnularRemesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAnularRemesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAnularRemesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                com.enerfrisoft.tools.Visual.setLookAndFeel();
                new FormAnularRemesa("testingTT", new DataSourceClass(), new DataSourceClass().conectar(1)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CODMOTIVOANULACION;
    private javax.swing.JButton anularRemesa;
    private javax.swing.JTextField consecutivoRemesa;
    private javax.swing.JTextField destinatario;
    private javax.swing.JTextField fechaDeRegisto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> motivoAnulacion;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JTextField remitente;
    // End of variables declaration//GEN-END:variables
}
