// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilacin R1)
// Generated source version: 1.1.3

package wsdl;

public interface IBPMServices extends java.rmi.Remote {
    public java.lang.String atenderMensajeRNDC(java.lang.String request) throws 
         java.rmi.RemoteException;
    public java.lang.String atenderMensajeBPM(java.lang.String request) throws 
         java.rmi.RemoteException;
}
