// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilacin R1)
// Generated source version: 1.1.3

package wsdl;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class IBPMServicesservice_SerializerRegistry implements SerializerConstants {
    public IBPMServicesservice_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("urn:BPMServicesIntf-IBPMServices", "AtenderMensajeBPMResponse");
            CombinedSerializer serializer = new wsdl.IBPMServices_AtenderMensajeBPM_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wsdl.IBPMServices_AtenderMensajeBPM_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:BPMServicesIntf-IBPMServices", "AtenderMensajeRNDCResponse");
            CombinedSerializer serializer = new wsdl.IBPMServices_AtenderMensajeRNDC_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wsdl.IBPMServices_AtenderMensajeRNDC_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:BPMServicesIntf-IBPMServices", "AtenderMensajeRNDC");
            CombinedSerializer serializer = new wsdl.IBPMServices_AtenderMensajeRNDC_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wsdl.IBPMServices_AtenderMensajeRNDC_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:BPMServicesIntf-IBPMServices", "AtenderMensajeBPM");
            CombinedSerializer serializer = new wsdl.IBPMServices_AtenderMensajeBPM_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wsdl.IBPMServices_AtenderMensajeBPM_RequestStruct.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
