// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilacin R1)
// Generated source version: 1.1.3

package wsdl;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class IBPMServicesservice_Impl extends com.sun.xml.rpc.client.BasicService implements IBPMServicesservice {
    private static final QName serviceName = new QName("http://tempuri.org/", "IBPMServicesservice");
    private static final QName ns1_IBPMServicesPort_QNAME = new QName("http://tempuri.org/", "IBPMServicesPort");
    private static final Class IBPMServices_PortClass = wsdl.IBPMServices.class;
    
    public IBPMServicesservice_Impl() {
        super(serviceName, new QName[] {
                        ns1_IBPMServicesPort_QNAME
                    },
            new wsdl.IBPMServicesservice_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_IBPMServicesPort_QNAME) &&
                serviceDefInterface.equals(IBPMServices_PortClass)) {
                return getIBPMServicesPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(IBPMServices_PortClass)) {
                return getIBPMServicesPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public wsdl.IBPMServices getIBPMServicesPort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_IBPMServicesPort_QNAME));
        handlerChain.setRoles(roles);
        wsdl.IBPMServices_Stub stub = new wsdl.IBPMServices_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
