// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilacin R1)
// Generated source version: 1.1.3

package wsdl;


public class IBPMServices_AtenderMensajeBPM_ResponseStruct {
    protected java.lang.String _return;
    
    public IBPMServices_AtenderMensajeBPM_ResponseStruct() {
    }
    
    public IBPMServices_AtenderMensajeBPM_ResponseStruct(java.lang.String _return) {
        this._return = _return;
    }
    
    public java.lang.String get_return() {
        return _return;
    }
    
    public void set_return(java.lang.String _return) {
        this._return = _return;
    }
}
