// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilacin R1)
// Generated source version: 1.1.3

package wsdl;

import javax.xml.rpc.*;

public interface IBPMServicesservice extends javax.xml.rpc.Service {
    public wsdl.IBPMServices getIBPMServicesPort() throws ServiceException;
}
