// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilacin R1)
// Generated source version: 1.1.3

package wsdl;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class IBPMServices_AtenderMensajeBPM_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private wsdl.IBPMServices_AtenderMensajeBPM_RequestStruct _instance;
    private java.lang.String request;
    private static final int myREQUEST_INDEX = 0;
    
    public IBPMServices_AtenderMensajeBPM_RequestStruct_SOAPBuilder() {
    }
    
    public void setRequest(java.lang.String request) {
        this.request = request;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myREQUEST_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myREQUEST_INDEX:
                    _instance.setRequest((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (wsdl.IBPMServices_AtenderMensajeBPM_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
