// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilacin R1)
// Generated source version: 1.1.3

package wsdl;


public class IBPMServices_AtenderMensajeBPM_RequestStruct {
    protected java.lang.String request;
    
    public IBPMServices_AtenderMensajeBPM_RequestStruct() {
    }
    
    public IBPMServices_AtenderMensajeBPM_RequestStruct(java.lang.String request) {
        this.request = request;
    }
    
    public java.lang.String getRequest() {
        return request;
    }
    
    public void setRequest(java.lang.String request) {
        this.request = request;
    }
}
