/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.enerfrisoft.tercero;

import com.enerfrisoft.dao.DataSourceClass;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import com.enerfrisoft.error.QueryError;
import com.enerfrisoft.sede.Sede;
import com.enerfrisoft.vehiculo.Vehiculo;
import com.enerfrisoft.vehiculo.XMLVehiculo;
import com.enerfrisoft.manifiesto.ManifiestoDAO;
import com.enerfrisoft.dao.ParametrosDAO;
import com.enerfrisoft.modal.Modal;
import com.enerfrisoft.openForm.OpenForm;
import com.enerfrisoft.remesa.RemesaDAO;
import com.enerfrisoft.tercero.Tercero;
import com.enerfrisoft.tools.Visual;
import com.enerfrisoft.tercero.XMLTercero;
import com.enerfrisoft.tools.Data;
import com.enerfrisoft.tools.Parser;
import com.enerfrisoft.tools.Items;
import com.enerfrisoft.tools.UniversalDAO;
import com.enerfrisoft.tools.VerifyConnection;
import com.enerfrisoft.viewPanel.FormViewPanel;
import java.rmi.RemoteException;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import wsdl.*;

/**
 *
 * @author Usuario
 */
public class FormTerceros extends javax.swing.JFrame {

    private String username;
    private TextAutoCompleter acNUMIDTERCERO;
    private TextAutoCompleter acEXPEDICION;
    private Boolean updateTercero;
    private Boolean updateSede;
    private DataSourceClass dataSource;
    private Connection conn;
    private Connection defaultServerConn;

    /**
     * Creates new form FormTerceros
     */
    public FormTerceros(DataSourceClass dataSource, Connection conn, String username) {
        this.conn = conn;
        this.dataSource = dataSource;
        this.defaultServerConn = this.dataSource.conectar(0);

        this.username = username;
        this.updateTercero = false;
        this.updateSede = true;
        initComponents();
        buildAutoCompleterMunicipio();
        fillEXPEDICION();
        connectionStatus.doClick();
        Visual.windowIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        limpiarCaracteristicas = new javax.swing.JButton();
        connectionStatus = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TIPOIDTERCERO = new javax.swing.JComboBox<>();
        NUMIDTERCERO = new javax.swing.JTextField();
        NOMIDTERCERO = new javax.swing.JTextField();
        PRIMERAPELLIDOIDTERCERO = new javax.swing.JTextField();
        SEGUNDOAPELLIDOIDTERCERO = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        CODTIPOIDTERCERO = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        EXPEDICION = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CODMUNICIPIORNDC = new javax.swing.JTextField();
        NOMSEDETERCERO = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CODSEDETERCERO = new javax.swing.JTextField();
        NUMTELEFONOCONTACTO = new javax.swing.JTextField();
        NUMCELULARPERSONA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NOMENCLATURADIRECCION = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        modelCODSEDETERCERO = new javax.swing.JComboBox<>();
        addSede = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CODCATEGORIALICENCIACONDUCCION = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        FECHAVENCIMIENTOLICENCIA = new com.toedter.calendar.JDateChooser();
        NUMLICENCIACONDUCCION = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoAdicional = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        registrar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        remesa = new javax.swing.JMenuItem();
        manifiesto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        registrarTerceros = new javax.swing.JMenuItem();
        registrarVehiculos = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        acercaDe = new javax.swing.JMenuItem();

        setTitle("Registro terceros");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane1.setOpaque(true);

        limpiarCaracteristicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/enerfrisoft/gui/sources/limpiar.png"))); // NOI18N
        limpiarCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCaracteristicasActionPerformed(evt);
            }
        });

        connectionStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/enerfrisoft/gui/sources/connection.png"))); // NOI18N
        connectionStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionStatusActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Terceros y Conductores");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Datos generales");

        jLabel1.setText("Tipo identificación");

        jLabel2.setText("Numero de Identificación");

        jLabel3.setText("Nombre");

        jLabel4.setText("Primer Apellido");

        jLabel5.setText("Segundo Apellido");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        TIPOIDTERCERO.setModel(ManifiestoDAO.tipo_id(conn));
        TIPOIDTERCERO.setSelectedItem(null);
        TIPOIDTERCERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPOIDTERCEROActionPerformed(evt);
            }
        });

        jLabel21.setText("Email");

        CODTIPOIDTERCERO.setEditable(false);

        jLabel27.setText("Expedición");

        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EXPEDICION))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TIPOIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CODTIPOIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NUMIDTERCERO))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NOMIDTERCERO))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EMAIL)
                                    .addComponent(SEGUNDOAPELLIDOIDTERCERO)
                                    .addComponent(PRIMERAPELLIDOIDTERCERO))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(TIPOIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CODTIPOIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(NUMIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(EXPEDICION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(NOMIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(PRIMERAPELLIDOIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SEGUNDOAPELLIDOIDTERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Datos de ubicación");

        jLabel10.setText("Nombre Sede");

        jLabel11.setText("Teléfono fijo");

        jLabel13.setText("Municipio ");

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");

        jLabel17.setText("Celular");

        jLabel20.setText("Codigo Sede");

        CODSEDETERCERO.setEditable(false);
        CODSEDETERCERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODSEDETERCEROActionPerformed(evt);
            }
        });

        jLabel12.setText("Dirección");

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");

        NOMENCLATURADIRECCION.setEditable(false);

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        modelCODSEDETERCERO.setToolTipText("Este campo solo se usa para modificar sedes ya existentes");
        modelCODSEDETERCERO.setEnabled(false);
        modelCODSEDETERCERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelCODSEDETERCEROActionPerformed(evt);
            }
        });

        addSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/enerfrisoft/gui/sources/Plus_16px.png"))); // NOI18N
        addSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CODMUNICIPIORNDC))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NUMCELULARPERSONA)
                                            .addComponent(NUMTELEFONOCONTACTO)
                                            .addComponent(NOMSEDETERCERO)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(modelCODSEDETERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CODSEDETERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(addSede, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NOMENCLATURADIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(modelCODSEDETERCERO, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CODSEDETERCERO, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(addSede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NOMSEDETERCERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(NUMTELEFONOCONTACTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(NUMCELULARPERSONA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NOMENCLATURADIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19)
                    .addComponent(CODMUNICIPIORNDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Datos de Licencia");

        jLabel23.setText("Categoria Lincencia");

        CODCATEGORIALICENCIACONDUCCION.setModel(RemesaDAO.getCODCATEGORIALICENCIACONDUCCION(conn)
        );
        CODCATEGORIALICENCIACONDUCCION.setSelectedItem(null);

        jLabel24.setText("Lincencia");

        jLabel25.setText("Vencimiento");

        FECHAVENCIMIENTOLICENCIA.setDateFormatString("EEEE, dd MMMM yyyy");
        FECHAVENCIMIENTOLICENCIA.setMinSelectableDate(new Date());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/enerfrisoft/gui/sources/limpiar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 42, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FECHAVENCIMIENTOLICENCIA, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(CODCATEGORIALICENCIACONDUCCION, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NUMLICENCIACONDUCCION))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(CODCATEGORIALICENCIACONDUCCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(NUMLICENCIACONDUCCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FECHAVENCIMIENTOLICENCIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Información Adicional");

        infoAdicional.setColumns(20);
        infoAdicional.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        infoAdicional.setLineWrap(true);
        infoAdicional.setRows(1);
        jScrollPane2.setViewportView(infoAdicional);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/enerfrisoft/gui/sources/tabla.png"))); // NOI18N
        jButton1.setToolTipText("Mostrar registros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(limpiarCaracteristicas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(connectionStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectionStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiarCaracteristicas))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(limpiarCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(connectionStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jLayeredPane1);

        jMenu3.setText("Archivo");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        registrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        registrar.setMnemonic('G');
        registrar.setText("Registrar Tercero");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jMenu3.add(registrar);
        jMenu3.add(jSeparator2);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu3.add(salir);

        jMenuBar1.add(jMenu3);

        jMenu1.setMnemonic('F');
        jMenu1.setText("Formularios");

        remesa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        remesa.setMnemonic('R');
        remesa.setText("Remesa");
        remesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remesaActionPerformed(evt);
            }
        });
        jMenu1.add(remesa);

        manifiesto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        manifiesto.setMnemonic('M');
        manifiesto.setText("Manifiesto");
        manifiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manifiestoActionPerformed(evt);
            }
        });
        jMenu1.add(manifiesto);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Herramientas");

        registrarTerceros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        registrarTerceros.setText("Registrar Terceros y Conductores");
        registrarTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTercerosActionPerformed(evt);
            }
        });
        jMenu4.add(registrarTerceros);

        registrarVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        registrarVehiculos.setText("Registrar Vehiculos y Remolques");
        registrarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVehiculosActionPerformed(evt);
            }
        });
        jMenu4.add(registrarVehiculos);

        jMenuBar1.add(jMenu4);

        ayuda.setText("Opciones");

        acercaDe.setMnemonic('A');
        acercaDe.setText("Acerca de");
        acercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeActionPerformed(evt);
            }
        });
        ayuda.add(acercaDe);

        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buildAutoCompleterNUMIDTERCERO() {
        acNUMIDTERCERO = new TextAutoCompleter(NUMIDTERCERO, new AutoCompleterCallback() {
            @Override
            public void callback(Object o) {
                updateTercero = true;

//                if (!TIPOIDTERCERO.getSelectedItem().toString().equals("NIT")) {
//                    addSede.setEnabled(false);
//                }
                //campo expedicion
                String expedicion = UniversalDAO.getString(""
                        + "select municipio.nombre "
                        + "from municipio,tercero "
                        + "where "
                        + "tercero.NUMIDTERCERO = '" + o.toString() + "' and "
                        + "municipio.id = tercero.EXPEDICION", conn);
                EXPEDICION.setText(expedicion);

                //campo nombre
                String nombre = UniversalDAO.getString(""
                        + "select coalesce(NOMIDTERCERO,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                NOMIDTERCERO.setText(nombre);

                //campo primer apellido
                String primerApellido = UniversalDAO.getString(""
                        + "select coalesce(PRIMERAPELLIDOIDTERCERO,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                PRIMERAPELLIDOIDTERCERO.setText(primerApellido);

                //campo segundo apellido
                String segundoApellido = UniversalDAO.getString(""
                        + "select coalesce(SEGUNDOAPELLIDOIDTERCERO,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                SEGUNDOAPELLIDOIDTERCERO.setText(segundoApellido);

                //email
                String email = UniversalDAO.getString(""
                        + "select coalesce(EMAIL,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                EMAIL.setText(email);

                //Categoria licencia
                String catLicencia = UniversalDAO.getString(""
                        + "select coalesce(CODCATEGORIALICENCIACONDUCCION,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                CODCATEGORIALICENCIACONDUCCION.setSelectedItem(catLicencia);

                //Numero de licencia
                String numLicencia = UniversalDAO.getString(""
                        + "select coalesce(NUMLICENCIACONDUCCION,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                NUMLICENCIACONDUCCION.setText(numLicencia);

                //Fecha de vencimiento licencia
                String sFECHAVENCIMIENTOLICENCIA = UniversalDAO.getString(""
                        + "select coalesce(FECHAVENCIMIENTOLICENCIA,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                try {
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(sFECHAVENCIMIENTOLICENCIA);
                    FECHAVENCIMIENTOLICENCIA.setDate(date);
                } catch (Exception e) {

                    System.out.println("date parsing FECHAVENCIMIENTOLICENCIA error");
                }

                //Sedes del tercero
                ComboBoxModel modelSede = UniversalDAO.getComboBoxModel(""
                        + "select sede.CODSEDETERCERO "
                        + "from sede "
                        + "where sede.NUMIDTERCERO = '" + o.toString() + "'", conn);
                modelCODSEDETERCERO.setModel(modelSede);
                modelCODSEDETERCERO.setSelectedItem(null);
                modelCODSEDETERCERO.setEnabled(true);

                //Info Adicional
                String info = UniversalDAO.getString(""
                        + "select coalesce(infoAdicional,'') "
                        + "from tercero "
                        + "where tercero.NUMIDTERCERO='" + o.toString() + "'", conn);
                infoAdicional.setText(info);
            }
        });
        acNUMIDTERCERO.removeAllItems();
        ArrayList<String> data = UniversalDAO.getArrayList(""
                + "select tercero.NUMIDTERCERO "
                + "from tercero "
                + "where tercero.CODTIPOIDTERCERO='" + CODTIPOIDTERCERO.getText() + "'", conn);
        for (int i = 0; i < data.size(); i++) {
            acNUMIDTERCERO.addItem(data.get(i));
        }

    }

    private void fillEXPEDICION() {
        acEXPEDICION = new TextAutoCompleter(EXPEDICION, new AutoCompleterCallback() {
            @Override
            public void callback(Object o) {

            }
        });
        acEXPEDICION.addItems(UniversalDAO.getArrayList(""
                + "select nombre "
                + "from municipio "
                + "", conn).toArray());
    }

    private void cleanDatosGenerales() {
        NUMIDTERCERO.setText("");
        NOMIDTERCERO.setText("");
        PRIMERAPELLIDOIDTERCERO.setText("");
        SEGUNDOAPELLIDOIDTERCERO.setText("");
        EMAIL.setText("");
    }

    private void FillNUMIDTERCERO(JComboBox TIPOIDTERCERO,
            TextAutoCompleter acNUMIDTERCERO,
            JTextField NUMIDTERCERO,
            JTextField NOMIDTERCERO,
            JTextField PRIMERAPELLIDOIDTERCERO,
            JTextField SEGUNDOAPELLIDOIDTERCERO,
            JTextField EMAIL,
            JTextField CODTIPOIDTERCERO
    ) {
        if (TIPOIDTERCERO.getSelectedItem() != null) {
            cleanDatosGenerales();
            String TIPOIDTERCERO_value = TIPOIDTERCERO.getSelectedItem().toString();
            String COD = UniversalDAO.getString(""
                    + "select cod "
                    + "from tipo_id "
                    + "where nombre='" + TIPOIDTERCERO_value + "';", conn);
            CODTIPOIDTERCERO.setText(COD);
            ArrayList<String> ids = UniversalDAO.getArrayList(""
                    + "select NUMIDTERCERO "
                    + "from tercero "
                    + "where CODTIPOIDTERCERO='" + COD + "'", conn);
            acNUMIDTERCERO.removeAllItems();
            for (int i = 0; i < ids.size(); i++) {
                acNUMIDTERCERO.addItem(ids.get(i));
            }
        }
    }

    private void CODSEDETERCEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODSEDETERCEROActionPerformed

    }//GEN-LAST:event_CODSEDETERCEROActionPerformed

    private void registrarTercero() {

        if (CODSEDETERCERO.getText().equals("")) {
            Modal.show("Aviso", "Debe agregar el código de sede del tercero", this, "", "warning");
        } else {
            if (EXPEDICION.getText().equals("") && !NUMLICENCIACONDUCCION.getText().equals("")) {
                Modal.show("Aviso", "Debe ingresar el municipio de expedición del documento del conductor", this, "", "warning");
            } else {
                Thread registro = new Thread(new RegistrarTercero(getValuesTercero(), updateTercero, getValuesSede(), updateSede, this, connectionStatus, NOMIDTERCERO.getText(), dataSource, conn));
                registro.start();
            }
        }
    }

    private void limpiarCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCaracteristicasActionPerformed
        limpiarCaracteristicas(true, true);
    }//GEN-LAST:event_limpiarCaracteristicasActionPerformed

    private void limpiarCaracteristicas(Boolean flag, Boolean flag2) {
        if (flag2) {
            addSede.setEnabled(true);
        }
        this.updateTercero = false;
        this.updateSede = true;
        CODSEDETERCERO.setEditable(false);
        CODCATEGORIALICENCIACONDUCCION.setSelectedItem(null);
        CODMUNICIPIORNDC.setText("");
        CODSEDETERCERO.setText("");
        if (flag) {
            TIPOIDTERCERO.setSelectedItem(null);
        }
        EMAIL.setText("");
        EXPEDICION.setEnabled(true);
        EXPEDICION.setText("");
        FECHAVENCIMIENTOLICENCIA.setDate(null);
        NOMENCLATURADIRECCION.setText("");
        NOMIDTERCERO.setText("");
        NOMSEDETERCERO.setText("");
        NUMCELULARPERSONA.setText("");
        NUMIDTERCERO.setText("");
        NUMLICENCIACONDUCCION.setText("");
        NUMTELEFONOCONTACTO.setText("");
        PRIMERAPELLIDOIDTERCERO.setText("");
        SEGUNDOAPELLIDOIDTERCERO.setText("");
        infoAdicional.setText("");
        modelCODSEDETERCERO.setSelectedItem(null);
        modelCODSEDETERCERO.setEnabled(false);
        CODTIPOIDTERCERO.setText("");
    }

    private void connectionStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionStatusActionPerformed
        try {
            Thread verificacion = new Thread(new VerifyConnection(connectionStatus, this));
            verificacion.start();
        } catch (Exception e) {
            Thread report = new Thread(new QueryError(new com.enerfrisoft.error.Error(e)));
            report.start();

        }
    }//GEN-LAST:event_connectionStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openFormViewTerceros(dataSource, conn);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void openFormViewTerceros(DataSourceClass dataSource,Connection conn) {
        String[] preModel = {"Conductores", "Empresas", "Otros"};
        DefaultComboBoxModel model = new DefaultComboBoxModel(preModel);
        String[] querys = {
            "select * from terceros where TIPO='Cédula' and LICENCIA!=''",
            "select TIPO,ID,NOMBRE,TEL,CEL,COD_SEDE,SEDE,DIRECCIÓN,MUNICIPIO,EMAIL,CREADOR,FECHA "
            + "from terceros where TIPO='NIT'",
            "select TIPO,ID,NOMBRE,APELLIDO1,APELLIDO2,TEL,CEL,SEDE,DIRECCIÓN,MUNICIPIO,EMAIL,CREADOR,FECHA "
            + "from terceros where TIPO!='NIT' and LICENCIA is null"
        };
        OpenForm.view("Terceros", querys, model, dataSource, conn);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CLEARDATOSDELICENCIA();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Visual.setLookAndFeel();
        FormEditarDireccion f = new FormEditarDireccion(dataSource, conn, this);
        f.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        registrarTercero();
    }//GEN-LAST:event_registrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void remesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remesaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                com.enerfrisoft.tools.Visual.setLookAndFeel();
                new com.enerfrisoft.remesa.FormRemesa(dataSource, conn, username).setVisible(true);
            }
        });
    }//GEN-LAST:event_remesaActionPerformed

    private void manifiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manifiestoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                com.enerfrisoft.tools.Visual.setLookAndFeel();
                new com.enerfrisoft.manifiesto.FormManifiesto(username, dataSource, conn).setVisible(true);
            }
        });
    }//GEN-LAST:event_manifiestoActionPerformed

    private void registrarTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTercerosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                com.enerfrisoft.tools.Visual.setLookAndFeel();
                new com.enerfrisoft.tercero.FormTerceros(dataSource, conn, username).setVisible(true);
            }
        });
    }//GEN-LAST:event_registrarTercerosActionPerformed

    private void registrarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVehiculosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                com.enerfrisoft.tools.Visual.setLookAndFeel();
                new com.enerfrisoft.vehiculo.FormVehiculos(dataSource, conn, username).setVisible(true);
            }
        });
    }//GEN-LAST:event_registrarVehiculosActionPerformed

    private void acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                com.enerfrisoft.tools.Visual.setLookAndFeel();
                new com.enerfrisoft.acercaDe.FormAcercaDe().setVisible(true);
            }
        });
    }//GEN-LAST:event_acercaDeActionPerformed

    private void modelCODSEDETERCEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelCODSEDETERCEROActionPerformed
        if (TIPOIDTERCERO.getSelectedItem() != null && modelCODSEDETERCERO.getSelectedItem() != null) {
            CODSEDETERCERO.setEditable(false);
            CODSEDETERCERO.setText(modelCODSEDETERCERO.getSelectedItem().toString());
            String codSedeTercero = modelCODSEDETERCERO.getSelectedItem().toString();

            //Nombre Sede Tercero
            String sNOMSEDETERCERO = UniversalDAO.getString(""
                    + "select coalesce(NOMSEDETERCERO,'') "
                    + "from sede "
                    + "where sede.NUMIDTERCERO = '" + NUMIDTERCERO.getText() + "' and "
                    + "sede.CODSEDETERCERO = '" + codSedeTercero + "'", conn);
            NOMSEDETERCERO.setText(sNOMSEDETERCERO);

            //Telefono
            String sNUMTELEFONOCONTACTO = UniversalDAO.getString(""
                    + "select coalesce(NUMTELEFONOCONTACTO,'') "
                    + "from sede "
                    + "where sede.NUMIDTERCERO = '" + NUMIDTERCERO.getText() + "' and "
                    + "sede.CODSEDETERCERO = '" + codSedeTercero + "'", conn);
            NUMTELEFONOCONTACTO.setText(sNUMTELEFONOCONTACTO);

            //Telefono celular
            String sNUMCELULARPERSONA = UniversalDAO.getString(""
                    + "select coalesce(NUMCELULARPERSONA,'') "
                    + "from sede "
                    + "where sede.NUMIDTERCERO = '" + NUMIDTERCERO.getText() + "' and "
                    + "sede.CODSEDETERCERO = '" + codSedeTercero + "'", conn);
            NUMCELULARPERSONA.setText(sNUMCELULARPERSONA);

            //Nomenclatura direccion
            String sNOMENCLATURADIRECCION = UniversalDAO.getString(""
                    + "select coalesce(NOMENCLATURADIRECCION,'') "
                    + "from sede "
                    + "where sede.NUMIDTERCERO = '" + NUMIDTERCERO.getText() + "' and "
                    + "sede.CODSEDETERCERO = '" + codSedeTercero + "'", conn);
            NOMENCLATURADIRECCION.setText(sNOMENCLATURADIRECCION);

            //Municipio dirección
            String sCODMUNICIPIORNDC = UniversalDAO.getString(""
                    + "select CODMUNICIPIORNDC "
                    + "from sede "
                    + "where sede.NUMIDTERCERO = '" + NUMIDTERCERO.getText() + "' and "
                    + "sede.CODSEDETERCERO = '" + codSedeTercero + "'", conn);
            String nombreMunicipio = UniversalDAO.getString(""
                    + "select municipio.nombre "
                    + "from municipio "
                    + "where municipio.id = '" + sCODMUNICIPIORNDC + "'", conn);
            CODMUNICIPIORNDC.setText(nombreMunicipio);
        }
    }//GEN-LAST:event_modelCODSEDETERCEROActionPerformed

    private void TIPOIDTERCEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPOIDTERCEROActionPerformed
        if (TIPOIDTERCERO.getSelectedItem() != null) {
            if (TIPOIDTERCERO.getSelectedItem().toString().equals("NIT")) {
                EXPEDICION.setEnabled(false);
                CODCATEGORIALICENCIACONDUCCION.setEnabled(false);
                NUMLICENCIACONDUCCION.setEditable(false);
                FECHAVENCIMIENTOLICENCIA.setEnabled(false);
            }

            //cod tipoid tercero
            String tipoId = UniversalDAO.getString(""
                    + "select tipo_id.cod "
                    + "from tipo_id "
                    + "where tipo_id.nombre = '" + TIPOIDTERCERO.getSelectedItem().toString() + "'", conn);
            CODTIPOIDTERCERO.setText(tipoId);

            buildAutoCompleterNUMIDTERCERO();

            limpiarCaracteristicas(false, false);
            if (TIPOIDTERCERO.getSelectedItem().toString().equals("NIT")) {
                EXPEDICION.setEnabled(false);
            }
        }
    }//GEN-LAST:event_TIPOIDTERCEROActionPerformed

    private void cleanDatosUbicacion() {
        modelCODSEDETERCERO.setSelectedItem(null);
        modelCODSEDETERCERO.setEnabled(false);
        CODSEDETERCERO.setText("");
        CODSEDETERCERO.setEnabled(true);
        NOMSEDETERCERO.setText("");
        NUMTELEFONOCONTACTO.setText("");
        NUMCELULARPERSONA.setText("");
        NOMENCLATURADIRECCION.setText("");
        CODMUNICIPIORNDC.setText("");
    }

    private void addSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSedeActionPerformed
        cleanDatosUbicacion();
        this.updateSede = false;
        CODSEDETERCERO.setEditable(true);
    }//GEN-LAST:event_addSedeActionPerformed

    public void setNOMENCLATURADIRECCION(String sNOMENCLATURADIRECCION) {
        NOMENCLATURADIRECCION.setText(sNOMENCLATURADIRECCION);
    }

    public String getNOMENCLATURADIRECCION() {
        return NOMENCLATURADIRECCION.getText();
    }

    private void CLEARDATOSDELICENCIA() {
        if (TIPOIDTERCERO.getSelectedItem() != null) {
            if (!TIPOIDTERCERO.getSelectedItem().toString().equals("NIT")) {
                CODCATEGORIALICENCIACONDUCCION.setSelectedItem(null);
                NUMLICENCIACONDUCCION.setText("");
                FECHAVENCIMIENTOLICENCIA.setDate(null);
                CODCATEGORIALICENCIACONDUCCION.setEnabled(true);
                NUMLICENCIACONDUCCION.setEnabled(true);
                FECHAVENCIMIENTOLICENCIA.setEnabled(true);
            }
        }
    }

    private Sede getValuesSede() {
        Sede sede = new Sede();
        Data.auth(sede, conn);

        try {
            sede.setNUMTELEFONOCONTACTO(NUMTELEFONOCONTACTO.getText());
            sede.setNUMCELULARPERSONA(NUMCELULARPERSONA.getText());
            sede.setNOMENCLATURADIRECCION(NOMENCLATURADIRECCION.getText());
            sede.setCODMUNICIPIORNDC(UniversalDAO.getCODMUNICIPIORNDC(CODMUNICIPIORNDC.getText(), conn));
            sede.setCODSEDETERCERO(CODSEDETERCERO.getText());
            sede.setNOMSEDETERCERO(NOMSEDETERCERO.getText());
            sede.setNUMIDTERCERO(NUMIDTERCERO.getText());
            sede.setUserLog(username);

            return sede;
        } catch (Exception e) {
            Thread report = new Thread(new QueryError(new com.enerfrisoft.error.Error(e)));
            report.start();
        }
        return new Sede();
    }

    private Tercero getValuesTercero() {
        try {
            Tercero tercero = new Tercero();
            Data.auth(tercero, conn);
            tercero.setCODTIPOIDTERCERO(UniversalDAO.getCODTIPOID(Items.getValue(TIPOIDTERCERO), conn));
            tercero.setNUMIDTERCERO(NUMIDTERCERO.getText());
            tercero.setEXPEDICION(UniversalDAO.getString("select id from municipio where municipio.nombre = '" + EXPEDICION.getText() + "'", conn));
            tercero.setNOMIDTERCERO(NOMIDTERCERO.getText());
            tercero.setPRIMERAPELLIDOIDTERCERO(PRIMERAPELLIDOIDTERCERO.getText());
            tercero.setSEGUNDOAPELLIDOIDTERCERO(SEGUNDOAPELLIDOIDTERCERO.getText());
            tercero.setNUMTELEFONOCONTACTO(NUMTELEFONOCONTACTO.getText());
            tercero.setNUMCELULARPERSONA(NUMCELULARPERSONA.getText());
            tercero.setNOMENCLATURADIRECCION(NOMENCLATURADIRECCION.getText());
            tercero.setCODMUNICIPIORNDC(UniversalDAO.getCODMUNICIPIORNDC(CODMUNICIPIORNDC.getText(), conn));
            tercero.setCODSEDETERCERO(CODSEDETERCERO.getText());
            tercero.setNOMSEDETERCERO(NOMSEDETERCERO.getText());
            tercero.setNUMLICENCIACONDUCCION(NUMLICENCIACONDUCCION.getText());
            tercero.setCODCATEGORIALICENCIACONDUCCION(Items.getValue(CODCATEGORIALICENCIACONDUCCION));
            try {
                tercero.setFECHAVENCIMIENTOLICENCIA(FECHAVENCIMIENTOLICENCIA.getDate());
            } catch (Exception e) {
                tercero.setFECHAVENCIMIENTOLICENCIA(null);
            }
            tercero.setEMAIL(EMAIL.getText());
            tercero.setEstado("activo");
            tercero.setUserLog(this.username);
            tercero.setInfoAdicional(infoAdicional.getText());

            return tercero;
        } catch (Exception ex) {
            Thread report = new Thread(new QueryError(new com.enerfrisoft.error.Error(ex)));
            report.start();
            System.out.println(ex.getLocalizedMessage() + ":guardarTerceroActionPerformed");
            return null;
        }
    }

    private void buildAutoCompleterMunicipio() {
        TextAutoCompleter acCODMUNICIPIORNDC = new TextAutoCompleter(CODMUNICIPIORNDC, new AutoCompleterCallback() {
            @Override
            public void callback(Object o) {

            }
        });

        ArrayList<String> municipios = ManifiestoDAO.getMunicipios(conn);
        for (int i = 0; i < municipios.size(); i++) {
            acCODMUNICIPIORNDC.addItem(municipios.get(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Visual.setLookAndFeel();
                new FormTerceros(new DataSourceClass(), new DataSourceClass().conectar(1), "testingTT").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CODCATEGORIALICENCIACONDUCCION;
    private javax.swing.JTextField CODMUNICIPIORNDC;
    private javax.swing.JTextField CODSEDETERCERO;
    private javax.swing.JTextField CODTIPOIDTERCERO;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField EXPEDICION;
    private com.toedter.calendar.JDateChooser FECHAVENCIMIENTOLICENCIA;
    private javax.swing.JTextField NOMENCLATURADIRECCION;
    private javax.swing.JTextField NOMIDTERCERO;
    private javax.swing.JTextField NOMSEDETERCERO;
    private javax.swing.JTextField NUMCELULARPERSONA;
    private javax.swing.JTextField NUMIDTERCERO;
    private javax.swing.JTextField NUMLICENCIACONDUCCION;
    private javax.swing.JTextField NUMTELEFONOCONTACTO;
    private javax.swing.JTextField PRIMERAPELLIDOIDTERCERO;
    private javax.swing.JTextField SEGUNDOAPELLIDOIDTERCERO;
    private javax.swing.JComboBox<String> TIPOIDTERCERO;
    private javax.swing.JMenuItem acercaDe;
    private javax.swing.JButton addSede;
    private javax.swing.JMenu ayuda;
    private javax.swing.JButton connectionStatus;
    private javax.swing.JTextArea infoAdicional;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton limpiarCaracteristicas;
    private javax.swing.JMenuItem manifiesto;
    private javax.swing.JComboBox<String> modelCODSEDETERCERO;
    private javax.swing.JMenuItem registrar;
    private javax.swing.JMenuItem registrarTerceros;
    private javax.swing.JMenuItem registrarVehiculos;
    private javax.swing.JMenuItem remesa;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
